<?php
/**
 * Created by PhpStorm.
 * User: mrren
 * Date: 2019/1/12
 * Time: 10:01 AM
 */

namespace epii\admin\center\app;


use epii\admin\center\common\_controller;
use epii\admin\center\libs\Tools;
use epii\admin\ui\lib\epiiadmin\jscmd\Alert;
use epii\admin\ui\lib\epiiadmin\jscmd\JsCmd;
use think\Db;

class install extends _controller
{

    private static $is_install = null;

    public function init()
    {
        if (self::$is_install !== false) {
            header("location:" . Tools::get_web_root());
            exit;
        }
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function index()
    {
        $this->adminUiDisplay("install/index", "安装程序");
    }

    public function config()
    {


        if ($_POST) {
            $config_dir = Tools::getVendorDir() . "/../config";

            if (!is_dir($config_dir)) {
                if (!mkdir($config_dir, 0777, true)) {
                    return JsCmd::make()->addCmd(Alert::make()->msg("请确保有创建文件夹" . $config_dir . "的权限")->onOk(null))->run();
                }
            }



            $config = $_POST;
            \think\Db::setConfig($_POST);
             $db_has = Db::query("show databases ".$config["database"]);
             var_dump($db_has);
             exit;
            file_put_contents(Tools::getVendorDir() . "/../config/db.conf.php", "<?php return  " . var_export($_POST, true) . " ;");
        } else {
            $this->adminUiDisplay("install/config", "安装程序");
        }

    }


    public static function isInstall()
    {
        if (self::$is_install === null) {
            if (file_exists(Tools::getVendorDir() . "/../config/db.conf.php")) {
                self::$is_install = true;
            } else {
                self::$is_install = false;
            }
        }
        return self::$is_install;

    }

}

 